name: Javadoc

on:
  push:
    branches: [ "main-v1.5" ]

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate Javadoc with Maven
        run: mvn javadoc:javadoc

      - name: Copy to Documentation Website Location
        run: |
          rm -rf docs
          cp -rf target/site/apidocs/. docs
          
      - name: Commit files
        run: |
          git config --local user.name "javadoc"
          git add ./docs
          git commit -m "Updating the repository GitHub html pages in the docs folder"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
