name: Java CI with Maven

on:
  push:
    branches: [ "main-v1.5" ]
  pull_request:
    branches: [ "main-v1.5" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create directory and copy jar
      run: mkdir staging && cp target/*.jar staging
    - name: Upload jar artifact
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
